### ISSUE TITLE
Got FileNotFoundException when tried to run

### ISSUE THREAD

**Issue by gzoller** [studiodev/json-bidrequests-benchmark-scala#2]
Hello,

I wanted to run your benchmark tool.  I cloned the repo and copy/pasted the sbt command in your README.  Got this error below.  Looks like there's some needed file not included in the repo?

[info] java.io.FileNotFoundException: /home/julien/work/perso/json-benchmark/test-data/1 (No such file or directory)
[info] 	at java.io.FileInputStream.open0(Native Method)
[info] 	at java.io.FileInputStream.open(FileInputStream.java:195)
[info] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[info] 	at scala.io.Source$.fromFile(Source.scala:91)
[info] 	at scala.io.Source$.fromFile(Source.scala:76)
[info] 	at benchs.ReadersBenchmark.<init>(ReadersBenchmark.scala:12)
[info] 	at benchs.OneFileReadersbenchmarks.<init>(ReadersBenchmark.scala:46)
[info] 	at benchs.generated.OneFileReadersbenchmarks_jmhType_B1.<init>(OneFileReadersbenchmarks_jmhType_B1.java:3)
[info] 	at benchs.generated.OneFileReadersbenchmarks_jmhType_B2.<init>(OneFileReadersbenchmarks_jmhType_B2.java:3)
[info] 	at benchs.generated.OneFileReadersbenchmarks_jmhType_B3.<init>(OneFileReadersbenchmarks_jmhType_B3.java:2)
[info] 	at benchs.generated.OneFileReadersbenchmarks_jmhType.<init>(OneFileReadersbenchmarks_jmhType.java:2)
[info] 	at benchs.generated.OneFileReadersbenchmarks_bench_jmhTest._jmh_tryInit_f_onefilereadersbenchmarks0_G(OneFileReadersbenchmarks_bench_jmhTest.java:309)
[info] 	at benchs.generated.OneFileReadersbenchmarks_bench_jmhTest.bench_AverageTime(OneFileReadersbenchmarks_bench_jmhTest.java:119)
[info] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] 	at java.lang.reflect.Method.invoke(Method.java:497)
[info] 	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
[info] 	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:745)

**Comment by studiodev** [comment]
Hello,

The file used to run the test is very large, so I've not uploaded it on Github.
Feel free to contact me by mail or Twitter, and I will send you the file.

**Comment by studiodev** [comment]
Added a note on the readme about that.
